# Generated by Django 4.1.7 on 2023-03-19 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_auto_20230224_1914"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="image",
            field=models.ImageField(upload_to="brand", verbose_name="الصوره"),
        ),
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(max_length=100, verbose_name="الماركه"),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_brand",
                to="product.brand",
                verbose_name="الماركه",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(max_length=20000, verbose_name="وصف كامل"),
        ),
        migrations.AlterField(
            model_name="product",
            name="flag",
            field=models.CharField(
                choices=[("New", "New"), ("Feature", "Feature"), ("Sale", "Sale")],
                max_length=10,
                verbose_name="علامه",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="products", verbose_name="الصوره"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=120, verbose_name="الاسم"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(verbose_name="السعر"),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.IntegerField(verbose_name="الكود"),
        ),
        migrations.AlterField(
            model_name="product",
            name="subtitle",
            field=models.CharField(max_length=300, verbose_name="وصف مختصر"),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="rate",
            field=models.IntegerField(verbose_name="التقيم"),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="review",
            field=models.TextField(max_length=400, verbose_name="الراي"),
        ),
    ]
